<?php

//https://code.mu/ru/php/book/oop/overriding-of-parent-methods/
class User
{
    protected string $name;
    private int $age;

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }

    /**
     * @param string $name
     */
    public function setName(string $name): void
    {
        if (strlen($name) >= 3) {
            $this->name = $name;
        }
    }

    /**
     * @return int
     */
    public function getAge(): int
    {
        return $this->age;
    }

    /**
     * @param int $age
     */
    public function setAge(int $age): void
    {
        $this->age = $age;
    }
}

class Student extends User
{
    private int $course;

    public function setName(string $name): void
    {
        if (strlen($name) <= 10) {
            parent::setName($name); // TODO: Change the autogenerated stub
        }
    }

    /**
     * @return int
     */
    public function getCourse(): int
    {
        return $this->course;
    }

    /**
     * @param int $course
     */
    public function setCourse(int $course): void
    {
        $this->course = $course;
    }

}

$student = new Student();
$student->setName('kolya');
echo $student->getName();
$student->setName('djfhkwjhfwkjfbwg');
echo $student->getName();